# Generated by Django 5.0.3 on 2024-04-17 01:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversionmessage_sent_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversion',
            unique_together={('created_by', 'with_user')},
        ),
    ]
