# Generated by Django 5.0.3 on 2024-04-14 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_user_friends_user_friends_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendshiprequest',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('sent', 'sent'), ('rejected', 'rejected')], default='sent', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 14, 0, 32, 42, 459896)),
        ),
    ]
