# Generated by Django 5.0.3 on 2024-04-16 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendshiprequest',
            name='status',
            field=models.CharField(choices=[('rejected', 'rejected'), ('sent', 'sent'), ('accepted', 'accepted')], default='sent', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 16, 3, 30, 8, 724)),
        ),
    ]
