# Generated by Django 5.0.3 on 2024-04-16 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_friendshiprequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendshiprequest',
            name='status',
            field=models.CharField(choices=[('sent', 'sent'), ('rejected', 'rejected'), ('accepted', 'accepted')], default='sent', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 16, 4, 55, 10, 821348)),
        ),
    ]
