# Generated by Django 5.0.3 on 2024-04-19 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_alter_friendshiprequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendshiprequest',
            name='status',
            field=models.CharField(choices=[('sent', 'sent'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='sent', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 19, 3, 10, 24, 462873)),
        ),
    ]
