# Generated by Django 5.0.3 on 2024-04-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attachement',
            field=models.ManyToManyField(to='post.attachment'),
        ),
    ]
