# Generated by Django 5.0.3 on 2024-04-13 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_comments_count_alter_like_created_by_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
