# Generated by Django 5.0.3 on 2024-04-18 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_trend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trend',
            old_name='name',
            new_name='hashtag',
        ),
        migrations.RenameField(
            model_name='trend',
            old_name='counter',
            new_name='occurences',
        ),
    ]
